security:
    providers:
        OICUserProvider:
            id: waldo_oic_rp.user.provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: ~
            openidconnect:
                always_use_default_target_path: false
                default_target_path: /private/other
                target_path_parameter: ~
                login_path: /private
                use_referer: ~
                create_users: true

    access_control:
        #- { path: ^/, roles: [ROLE_OIC_USER] }
        - { path: ^/private, roles: [ROLE_OIC_USER, ROLE_APPLICATION_A, ROLE_APPLICATION_B] }

    role_hierarchy:
        ROLE_ADMIN: ['ROLE_APPLICATION_A', 'ROLE_APPLICATION_B']

parameters:
    roles:
        users:
            90342.ASDFJWFA: ['ROLE_OIC_USER', 'ROLE_APPLICATION_A']
            01921.FLANRJQW: ['ROLE_OIC_USER', 'ROLE_ADMIN']
            01922.FLANTEST: []
        default: ['ROLE_OIC_USER']



